---
title: "Leaflet Project"
author: "Alex Fennell"
date: "5/3/2022"
output: html_document
---

```{r libraries,message=FALSE,warning=FALSE,echo=FALSE}
library(leaflet)
library(rgeos)
library(rworldmap)
library(tidyverse)
library(stringdist)
```


```{r data read in,echo=FALSE}
    hapdat<-read.csv("world-happiness-report-2021.csv")
    wmap<-getMap(resolution='low')
    cent<-gCentroid(wmap,byid=TRUE)
    locations<-data.frame(cent)
    locations$Country<-rownames(locations)
    colnames(locations)<-c("longitude","latitude","Country")
```

```{r Location data and marker setup,echo=FALSE}
locations<-locations[-233,]
loc<-locations[amatch(hapdat$ï..Country.name,locations$Country,method='jw',maxDist=15),]
dat<-merge(loc,hapdat,by.x="Country",by.y="ï..Country.name",all=TRUE)
dat[150,c(2,3)]<-dat[151,c(2,3)]
dat[137,c(2,3)]<-dat[136,c(2,3)]
dat[55,c(2,3)]<-dat[54,c(2,3)]
dat2<-na.omit(dat)
mapdata<-dat2[,c(1,2,3,5,9,11)]
mapdata$markers <- paste0("Country: ",mapdata$Country, "<br>",
                  "Longitude: ",mapdata$longitude,"<br>",
                  "Latitude: ",mapdata$latitude,"<br>",
                  "Happiness: ",mapdata$Ladder.score,"<br>",
                  "Life Expectancy: ",mapdata$Healthy.life.expectancy)

```



## World Happiness and Life Expectancy

This map displays information about happiness within a country in addition to its 
life expectancy. Happiness is on a scale from 1-8 with 8 being the happiest. The
dataset was gathered from Kaggle and is updated yearly by government organizations.


```{r pressure, warning=FALSE,message=FALSE,echo=FALSE}
leafmap<-mapdata%>%
    leaflet()%>%
    addTiles()%>%
    addMarkers(popup = markers,clusterOptions = markerClusterOptions())
leafmap
```


